add test json

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,6 +17,24 @@ jobs:
         run: |
           ls -l viz/data/
           file viz/data/2024-12-02_delim-parcellaire-aoc.json
+          # Vérifier si le fichier JSON est valide avec jq
+          if ! jq empty viz/data/2024-12-02_delim-parcellaire-aoc.json > /dev/null 2>&1; then
+            echo "ERROR: JSON file is invalid or corrupted!" && exit 1
+          fi
+          echo "JSON file is valid."
+      
+      - name: Check JSON readability in R
+        run: |
+          Rscript -e '
+            library(jsonlite)
+            tryCatch({
+              data <- fromJSON("viz/data/2024-12-02_delim-parcellaire-aoc.json")
+              cat("JSON file successfully loaded into R.\n")
+            }, error = function(e) {
+              cat("ERROR: Failed to read JSON file in R.\n")
+              stop(e)
+            })
+          '
       
       - name: Set CRAN mirror for renv
         run: echo "RENV_CONFIG_REPOS_OVERRIDE=https://cran.r-project.org" >> ~/.Renviron
